-- MySQL Script generated by MySQL Workbench
-- Thu Jun  2 14:39:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_hero_games
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_hero_games
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_hero_games` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_hero_games` ;

-- -----------------------------------------------------
-- Table `db_hero_games`.`tb_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_hero_games`.`tb_categorias` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_hero_games`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_hero_games`.`tb_produtos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `data_lancamento` DATE NULL DEFAULT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  `disponivel` BIT(1) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `quantidade` INT NOT NULL,
  `valor` DOUBLE NOT NULL,
  `categorias_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKn3jnbr9iheqyuglqa94fqt6sl` (`categorias_id` ASC) VISIBLE,
  CONSTRAINT `FKn3jnbr9iheqyuglqa94fqt6sl`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `db_hero_games`.`tb_categorias` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
